### ISSUE TITLE
Crashes on production release on Android when using React Native 0.65+

### ISSUE THREAD

**Issue by csotiriou** [venits/native-forms#3]
Library worked fine with RN 0.64, but since upgrading, I get the following error when using it from a production build on Android:

```
2021-10-15 12:36:11.421 24821-24849/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: my.package.name PID: 24821
    com.facebook.react.common.JavascriptException: TypeError: o.scrollResponderScrollTo is not a function. (In 'o.scrollResponderScrollTo({x:e,y:n,animated:r})', 'o.scrollResponderScrollTo' is undefined), stack:
    <unknown>@978:46533
    <unknown>@978:46801
    <unknown>@978:48714
    value@37:3850
    <unknown>@37:828
    value@37:2503
    value@37:798
    value@-1
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)

```

To reproduce it, tap on any text field on any form.

I dug a little deeper, and I saw that this library depends on `react-native-keyboard-aware-scroll-view`, which seems to have an issue with RN0.64+ .

https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/494

I am not quite sure how and when this issue can be fixed, but for sure it makes nativeForms unusable right now.

EDIT: This is crashing on iOS, too.

**Comment by tomekvenits** [comment]
Fixed in version `1.7.0`. Thanks 👍
